package Exception_Handling;

public class Catch_Try_Catch {
	
	public static void main(String[] args) {
		
		int a=10;
		int b=2;
		System.out.println("Before Exception");
	}
	catch
	Try_Try_Catch
		int c=a/b;
		System.out.println("Division="+c);
	}
	
	System.out.println("After Exception");

	

	}

}
