package Exception_Handling;

public class Try_Try_Catch {
	public static void main(String[] args) { 
		
		int a=20;
		int b=0;
		
		System.out.println("Before Exception");
		try {
		try {
			int c=a/b;
			System.out.println("Division="+c);
			
		} catch (Exception e) {
		
			
			
		
		
			System.out.println("After exception");
		
		}
	
}

